---
title: "Final Project 1 Pager"
author: "Connor McGeehan"
date: "2025-11-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

This project uses historical race data to build a predictive model that forecasts the top 40 finishers; All-Americans, at the NCAA Division III Cross Country National Championships in 2025. By analyzing performance trends, athlete progression, and race conditions, we aim to provide a model that rivals existing prediction systems like LACCTiC.

## Data

We will use data collected from the LACCTiC API. This API gives us access to meet results and specific athlete's racing history. We will use this to collect the following information about each athlete:

-   **Athlete ID** – A unique identifier for each athlete

-   **Year** – The year that the Athlete data is from

-   **Athlete Name** – The name of the Athlete

-   **Athlete Class** – Freshman, Sophomore, Junior, Senior, Graduate Student

-   **School** – NCAA Division III institution

-   **Number of Races Run** – The number of races that the athlete has competed in during the season

-   **Personal Record** – The athlete's fastest recorded time over 8k

-   **Season Record** – The athlete's fastest recorded 8k of the season

-   **Consistency** – Standard Deviation of the athlete's times across 8k for that season

-   **Days since Season PR** – As of the day of nationals, the number of days since they ran their fastest 8k

-   **All-American** – Binary result representing whether or not the athlete was an All-American at the national meet (1 is yes, 0 is no)

Additionally, we will collect race results for each athlete who raced at the national championship. These results will include:

-   **Athlete ID** – A unique identifier for each athlete

-   **Meet Data** – The day that the meet was run

-   **Meet Name** – The name of the meet

-   **Race Distance** – Typically 8k for men, but varies by race

-   **Time** – Official race finish time in seconds

-   **Place** – The position that the athlete finished the race in

## Questions

Who is going to be an All-American at the DIII 2025 XC National meet?

How does our model compare to the predictions created by LACCTiC?

## Stakeholders

Stakeholders could include a wide variety of people:

-   NCAA XC Coaches and Athletes

-   XC Fans and Spectators

-   High School Recruits interested in how different programs perform

-   Administrators and Athletics Departments from competing schools

## KPIs

-   Accuracy of model overall

-   Accuracy of model in comparison to LACCTiC

-   Models accuracy compared to predictions based off 8k season bests
