---
title: "EDA"
author: "Connor McGeehan"
date: "2025-11-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exploratory Data Analysis

### Data and Libraries

```{r}
athlete_data <- read.csv("../data/athletes.csv")
race_data <- read.csv("../data/races.csv")
library(tidyverse)
```

## Single-variable visualizations

**Number of Races Run**

```{r}
ggplot(athlete_data, aes(Number.of.Races.Run)) +
  geom_bar(fill="blue") + 
  labs(title="Number of Races Run Before National Meet", x="Number of Races", y="Number of Athletes")
```

**Personal Record**

```{r}
ggplot(athlete_data, aes(Personal.Record)) + 
  geom_histogram(fill="skyblue") +
  labs(title="Personal Record for XC 8k", x="Time (seconds)", y="Number of Athletes")
```

**Season Record**

```{r}
ggplot(athlete_data, aes(Season.Record)) + 
  geom_histogram(fill="skyblue") +
  labs(title="Season Record for XC 8k", x="Time (seconds)", y="Number of Athletes")
```

**Consistency**

```{r}
ggplot(athlete_data, aes(Consistency)) + 
  geom_histogram(fill="skyblue") +
  labs(title="Consistency of Performances", x="Standard Deviation of Times (seconds)", y="Number of Athletes")
```

**Days Since Season Record**

```{r}
ggplot(athlete_data, aes(Days.since.Season.PR)) + 
  geom_bar(fill="green") +
  labs(title="Days Since Season Record", x="Days", y="Number of Athletes")
```

**Time at Nationals**

```{r}
ggplot(race_data, aes(Time)) + 
  geom_histogram(fill="skyblue") +
  labs(title="Finishing Time at Nationals", x="Time (seconds)", y="Number of Athletes")
```

## Multiple Variables

**Comparing Different Variables to All-American Status**

Number of Races Run

```{r}
ggplot(athlete_data, aes(x=Number.of.Races.Run, fill=as.factor(All.American))) +
  geom_bar(position="fill") + 
  scale_fill_discrete(name = "All-American",
                      labels = c("No", "Yes")) +
  labs(title="All-American Status by Number of Races Run",
       x = "Number of Races Run",
        y = "Proportion of All-Americans")
```

Personal Record and Season Record

```{r}
athlete_data %>%
  filter(Personal.Record > 1350) %>%
  mutate(PR_SR = ifelse(Season.Record == Personal.Record,
                        "PR = SR",
                        "SR ≠ PR")) %>%
  ggplot(aes(x = Personal.Record, y = Season.Record, color = as.factor(All.American))) +
    geom_point() +
    scale_color_discrete(name="All-American", labels = c("0"="No", "1"="Yes")) +
    facet_wrap(~PR_SR) +
    labs(
      title = "All-American Status by Personal and Season Records",
      x = "Personal Record",
      y = "Season Record"
      )
```

Consistency

```{r}
ggplot(athlete_data, aes(x = Consistency, fill = as.factor(All.American))) +
    geom_density(alpha = 0.4) +
    scale_fill_manual(values = c("0" = "red", "1" = "blue"),
                      name = "All-American",
                      labels = c("No", "Yes")) +
    coord_cartesian(xlim = c(0, 150)) +
    labs(
        title = "Density of Consistency for All-Americans vs Non-All-Americans",
        x = "Consistency (Std Dev)",
        y = "Density"
    )
```

Days Since Season PR

```{r}
ggplot()
```
